#!/bin/sh
for f in direnvrc gitconfig gitignore gitallowedsigners zsh_aliases zshenv zshrc
do
  cp "${HOME}/.${f}" "${f}"
  if [ $f = "gitconfig" ]
  then
    sed -i '/token = /d' gitconfig
  fi
done
