#!/usr/bin/env bash
set -eu

export PASSPHRASE="$(head -n 1 "${HOME}/.backup_key")"
export AWS_ACCESS_KEY_ID=$(awk -F '=' '/aws_access_key_id/ {print $2}' $HOME/.aws/credentials | tr -d ' ')
export AWS_SECRET_ACCESS_KEY=$(awk -F '=' '/aws_secret_access_key/ {print $2}' $HOME/.aws/credentials | tr -d ' ')
SOURCE="/path/to/directory"
DEST="boto3+s3://bucket_name"

backup() {
  duplicity \
    --name backup \
    --allow-source-mismatch \
    --full-if-older-than 3M \
    --s3-use-ia \
    --asynchronous-upload \
    --s3-use-new-style \
    -v5 \
    --exclude-if-present ".owncloudsync.log" \
    --exclude-if-present ".sync*" \
    --exclude-if-present "Desktop.ini" \
    "${SOURCE}" "${DEST}"
}

verify() {
  duplicity verify \
    --name backup \
    -v5 \
    --exclude-if-present ".owncloudsync.log" \
    --exclude-if-present ".sync*" \
    --exclude-if-present "Desktop.ini" \
    "${DEST}" "${SOURCE}"
}

list() {
  duplicity list-current-files "${DEST}"
}

clean() {
  duplicity cleanup "${DEST}"
}

restore() {
  if [ "$#" -lt 3 ]
  then
    echo "Usage $0 restore <time (1D, 1M, 2023-01-01)> <destination> [<file>]"
    exit
  fi
  args=( "duplicity" "restore" "-v5" "--restore-time ${2}" )
  if [ "$#" -ge 4 ]
  then
    args+=( "--file-to-restore \"${4}\"" )
  fi
  args+=( "${DEST}" "\"${3}\"")
  echo "${args[@]}"
  eval "${args[@]}"
}

if [ "$#" -lt 1 ]
then
  echo "Usage $0 (backup|verify|restore|list|clean)"
  exit 1
fi
case "$1" in
  backup)
    backup
    ;;
  verify)
    verify
    ;;
  list)
    list
    ;;
  clean)
    clean
    ;;
  restore)
    restore "$@"
    ;;
  *)
    echo "Usage: $0 (backup|verify|restore|list|clean)"
    ;;
esac
